[package]
name = "bbox-processes-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbox-common = { path = "../bbox-common" }
actix-web = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
utoipa = { version = "0.1.1", features = ["actix_extras"] }
